name: trigger jenkins job
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://100d-18-200-97-133.eu.ngrok.io:8080"
        user: "umut"
        token: "1131b51ce5524d2afb5de0839dd8969cb0"
        job: "Deneme"
